version: '3.8'
services:
  web:
    build: .
    ports:
      - "5004:5004"
    depends_on:
      - rdb
  rdb:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local


  