name: terraform destroy

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

defaults:
  run:
    working-directory: infra

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v3

    - name: terraform init
      run: terraform init -reconfigure
    
    - name: Terraform destroy plan
      run: terraform plan -destroy

    - name: Terraform destroy
      run: terraform destroy -auto-approve